
import React from 'react';

/**
 * Main App Component
 * Welcome to your new application created with Devstudio.ai
 */

export default function App() {
  return (
    <div style={{ textAlign: 'center', padding: '50px' }}>
      <h1>Welcome to ai-assistant-2!</h1>
      <p>
        This app was generated by <strong>Devstudio.ai</strong>, your AI-powered
        app development tool.
      </p>
      <footer style={{ marginTop: '20px' }}>
        <p>Visit <a href="https://devstudio.ai">Devstudio.ai</a> for more.</p>
      </footer>
    </div>
  );
};
        